kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - git clone https://github.com/cdr/code-server
     - cd code-server
     - yarn build 1.41.1 .lkgr
     - yarn binary 1.41.1 .lkgr
     - yarn package 1.41.1 .lkgr
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - cd code-server
     - yarn build 1.41.1 .lkgr-alpine
     - yarn binary 1.41.1 .lkgr-alpine
     - yarn package 1.41.1 .lkgr-alpine
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: publish
   image: plugins/github-release
   settings:
     api_key:
        from_secret: gh-token
     files: release/*.tar.gz
   when:
     event: tag

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - git clone https://github.com/cdr/code-server
     - cd code-server
     - yarn build 1.41.1 .lkgr
     - yarn binary 1.41.1 .lkgr
     - yarn package 1.41.1 .lkgr
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - cd code-server
     - yarn build 1.41.1 .lkgr-alpine
     - yarn binary 1.41.1 .lkgr-alpine
     - yarn package 1.41.1 .lkgr-alpine
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: publish
   image: plugins/github-release
   settings:
     api_key:
        from_secret: gh-token
     files: release/*.tar.gz
   when:
     event: tag

---
kind: pipeline
type: docker
name: build-arm

platform:
  arch: arm

steps:

 - name: build
   image: node:12
   commands:
     - apt update && apt install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev
     - git clone https://github.com/cdr/code-server
     - cd code-server
     - yarn build 1.41.1 .lkgr
     - yarn binary 1.41.1 .lkgr
     - yarn package 1.41.1 .lkgr
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: build-alpine
   image: node:12-alpine
   commands:
     - apk add libxkbfile-dev libsecret-dev build-base git
     - cd code-server
     - yarn build 1.41.1 .lkgr-alpine
     - yarn binary 1.41.1 .lkgr-alpine
     - yarn package 1.41.1 .lkgr-alpine
   environment:
    GITHUB_TOKEN:
      from_secret: gh-token

 - name: publish
   image: plugins/github-release
   settings:
     api_key:
        from_secret: gh-token
     files: release/*.tar.gz
   when:
     event: tag